# Generated by Django 4.1.2 on 2022-11-22 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalFinding",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("disease", models.CharField(max_length=100)),
                ("medicine", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
