# Generated by Django 4.1.2 on 2022-12-04 21:22

from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FindingReadingRight",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalFinding",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                (
                    "disease",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=100)
                    ),
                ),
                (
                    "medicine",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=100)
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
