# Generated by Django 4.1.2 on 2022-12-04 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_system", "0001_initial"),
        ("medical_finding", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalfinding",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_system.patient"
            ),
        ),
        migrations.AddField(
            model_name="medicalfinding",
            name="treator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treator",
                to="user_system.doctor",
            ),
        ),
        migrations.AddField(
            model_name="findingreadingright",
            name="medical_finding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medical_finding.medicalfinding",
            ),
        ),
        migrations.AddField(
            model_name="findingreadingright",
            name="reader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
