# Generated by Django 4.1.2 on 2022-12-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_finding", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalfinding",
            old_name="medicine",
            new_name="comment",
        ),
    ]
