# Generated by Django 4.1.2 on 2022-12-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_finding", "0003_findingaccessright"),
    ]

    operations = [
        migrations.AddField(
            model_name="findingaccessright",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
