# Generated by Django 4.1.2 on 2022-12-10 09:40

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("medical_finding", "0003_rename_medicine_medicalfinding_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalfinding",
            name="comment",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300)),
        ),
    ]
