# Generated by Django 4.1.2 on 2022-12-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0005_alter_doctorprofile_user"),
        ("medical_finding", "0005_medicalfinding_diagnosed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalfinding",
            name="user",
        ),
        migrations.AddField(
            model_name="medicalfinding",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_system.patient",
            ),
            preserve_default=False,
        ),
    ]
