FROM cypress/browsers:node18.12.0-chrome107 as builder

# set working directory
# RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install chrome for protractor tests
#RUN sed -i -- 's&deb http://deb.debian.org/debian jessie-updates main&#deb http://deb.debian.org/debian jessie-updates main&g' /etc/apt/sources.list
#RUN apt-get update
#RUN apt-get install gnupg2 -y
#RUN apt-get install wget -y
#RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#RUN apt-get update
#RUN apt-get install libxss1
#RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#RUN apt-get install -yq google-chrome-stable

# install and cache app dependencies
# COPY package.json /usr/src/app/package.json
COPY package.json /usr/src/app/package.json
# RUN npm install -g @angular/cli --unsafe
RUN npm install --force
# add app
COPY . /usr/src/app

RUN npx cypress run