services:
  backend:
    build: 'backend/'
    command: >
      sh -c "python /code/manage.py makemigrations && python /code/manage.py migrate &&
             python /code/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/code # <-- mount the backend code for live development
      #- /static:/static
      - media_uploads:/code/media
    depends_on:
      - db
    env_file:
      - vars-dev.env
  frontend:
    build: 'frontend/healthmonitoring/'
    ports:
      - 4200:80
    env_file:
      - vars-dev.env
  cypress:
    image: cypress
    build:
      context: 'frontend/healthmonitoring/'
      dockerfile: Dockerfile-cypress
    container_name: cypress
    depends_on:
      - frontend
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - vars-dev.env
volumes:
  postgres_data:
  media_uploads:
