version: "3.9"

services:
  backend:
    build: 'backend/'
    command: >
      sh -c "python /code/manage.py makemigrations && python /code/manage.py migrate &&
             python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build:
      context: 'frontend/healthmonitoring/'
      dockerfile: Dockerfile
    ports:
      - 4200:80
  # cypress:
  #   build:
  #     context: 'frontend/healthmonitoring/'
  #     dockerfile: Dockerfile-cypress
  #   command: "npx cypress run "
  #   volumes:
  #     # - ./frontend/healthmonitoring/cypress:/cypress
  #     - ./frontend/healthmonitoring/cypress.config.ts:/cypress.config.ts
  #     - ./frontend/healthmonitoring/cypress/tsconfig.json:/tsconfig.json
  #   # build:
  #   #   context: 'frontend/healthmonitoring/'
  #   #   dockerfile: Dockerfile-cypress
  #   depends_on:
  #     - frontend
  #   # network_mode: 'host'
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
