# Generated by Django 4.1.2 on 2022-11-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"permissions": [("view_patient2", "Can view patient")]},
        ),
    ]
