# Generated by Django 4.1.2 on 2022-11-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="uid",
            new_name="id",
        ),
    ]
