# Generated by Django 4.1.2 on 2022-12-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                ],
                default="PATIENT",
                max_length=50,
            ),
        ),
    ]
