# Generated by Django 4.1.2 on 2022-11-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0002_alter_patient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={},
        ),
    ]
