# Generated by Django 4.1.2 on 2022-12-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0002_rename_uid_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
