# Generated by Django 4.1.2 on 2022-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0003_alter_patient_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
