# Generated by Django 4.1.2 on 2022-11-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0004_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="patient_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                ],
                default="PATIENT",
                max_length=50,
            ),
        ),
    ]
