# Generated by Django 4.1.2 on 2022-12-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0005_alter_doctorprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_email_verified",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
