# Generated by Django 4.1.2 on 2022-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_system",
            "0005_user_is_verified_alter_patientprofile_patient_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_verified",
            new_name="is_email_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="test_check",
            field=models.BooleanField(default=False),
        ),
    ]
