# Generated by Django 4.1.2 on 2022-11-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0006_rename_is_verified_user_is_email_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="test_check",
        ),
    ]
