# Generated by Django 4.1.2 on 2022-12-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0006_remove_user_is_email_verified_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
