# Generated by Django 4.1.2 on 2022-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0007_remove_user_test_check"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
