# Generated by Django 4.1.2 on 2022-12-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0007_patientprofile_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="birth_date",
        ),
    ]
