# Generated by Django 4.1.2 on 2022-12-04 18:34

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0008_remove_patientprofile_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
    ]
