# Generated by Django 4.1.2 on 2022-12-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical_finding", "0002_initial"),
        ("upload_files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="medical_finding",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medical_finding.medicalfinding",
            ),
        ),
    ]
