# Generated by Django 4.1.2 on 2022-12-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload_files", "0003_remove_file_owner_alter_file_medical_finding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file_name",
        ),
    ]
