
def get_media_type(file_name):
    if file_name.endswith('.pdf'):
        return 'application/pdf'
    elif file_name.endswith('.doc'):
        return 'application/msword'
    elif file_name.endswith('.docx'):
        return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    elif file_name.endswith('.xls'):
        return 'application/vnd.ms-excel'
    elif file_name.endswith('.xlsx'):
        return 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    elif file_name.endswith('.ppt'):
        return 'application/vnd.ms-powerpoint'
    elif file_name.endswith('.pptx'):
        return 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    elif file_name.endswith('.txt'):
        return 'text/plain'
    elif file_name.endswith('.png'):
        return 'image/png'
    elif file_name.endswith('.jpg'):
        return 'image/jpeg'
    elif file_name.endswith('.jpeg'):
        return 'image/jpeg'
    elif file_name.endswith('.gif'):
        return 'image/gif'
    elif file_name.endswith('.bmp'):
        return 'image/bmp'
    elif file_name.endswith('.tif'):
        return 'image/tiff'
    elif file_name.endswith('.tiff'):
        return 'image/tiff'
    elif file_name.endswith('.svg'):
        return 'image/svg+xml'    
    elif file_name.endswith('.zip'):
        return 'application/zip'
    elif file_name.endswith('.rar'):
        return 'application/x-rar-compressed'
    elif file_name.endswith('.7z'):
        return 'application/x-7z-compressed'
    elif file_name.endswith('.tar'):
        return 'application/x-tar'
    elif file_name.endswith('.gz'):
        return 'application/gzip'