# Generated by Django 4.1.2 on 2022-10-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arzt",
            fields=[
                ("aID", models.AutoField(primary_key=True, serialize=False)),
                ("bezeichnung", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Befund",
            fields=[
                ("bID", models.AutoField(primary_key=True, serialize=False)),
                ("krankheit", models.CharField(max_length=100)),
                ("medikament", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[("paID", models.AutoField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("peID", models.AutoField(primary_key=True, serialize=False)),
                ("vorname", models.CharField(max_length=100)),
                ("nachname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PatientenZugriff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HealthDashboard.befund",
                    ),
                ),
                (
                    "paID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HealthDashboard.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="peID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HealthDashboard.person"
            ),
        ),
        migrations.AddField(
            model_name="befund",
            name="paID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="HealthDashboard.patient",
            ),
        ),
        migrations.CreateModel(
            name="ArztZugriff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HealthDashboard.arzt",
                    ),
                ),
                (
                    "bID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HealthDashboard.befund",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="arzt",
            name="peID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HealthDashboard.person"
            ),
        ),
    ]
