name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Bhacaz/checkout-files@v2
        with:
          files: frontend/healthmonitoring
      - name: debug
        run: ls
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0 # use the explicit version number
        with:
          project: ./frontend/healthmonitoring
          build: npm run cy:run
