name: Test and Deploy Full

on:
  push:
    branches: [ main ]

jobs:
  backend-test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # the requirements.txt file is in backend/requirements.txt
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Lint with Flake8
    # the flake8 file is in backend/.flake8
      run: |
        pip install flake8
        flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 backend --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    # the manage.py file is in backend/manage.py
    - name: Run Django Tests
      run: |
        python backend/manage.py test auth
        python backend/manage.py test core
        python backend/manage.py test download_files
        python backend/manage.py test upload_files
        python backend/manage.py test user_system
        python backend/manage.py test medical_finding
  frontend-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: cd frontend/healthmonitoring && npm ci --force

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test:ci
    
    - name: Build
      run: npm run build:ci

  deploy:
    needs: [backend-test,frontend-test]
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: using remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/healthmon/repos/HealthMonitoring
            git pull
            docker-compose down
            docker-compose up -d --build --remove-orphans --force-recreate
            

